# ------------------------------------------------------------------
# Database credentials.
#
# Passwords are generated by Terraform, never typed by a human and
# never written into a values file. They are stored as encrypted SSM
# parameters and read at deploy time to create Kubernetes Secrets.
#
# SSM Parameter Store is used rather than Secrets Manager because it
# is free at this scale and has no deletion recovery window, so a
# destroy and rebuild cycle cannot be blocked by a reserved name.
# ------------------------------------------------------------------

resource "random_password" "catalog" {
  length  = 24
  special = false
}

resource "random_password" "orders" {
  length  = 24
  special = false
}

resource "aws_ssm_parameter" "catalog_password" {
  name        = "/${var.name_prefix}/catalog/db-password"
  description = "Master password for the catalog MySQL instance"
  type        = "SecureString"
  value       = random_password.catalog.result
}

resource "aws_ssm_parameter" "orders_password" {
  name        = "/${var.name_prefix}/orders/db-password"
  description = "Master password for the orders PostgreSQL instance"
  type        = "SecureString"
  value       = random_password.orders.result
}
